apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: cert-manager
  includeCRDs: true
  releaseName: cert-manager
  namespace: cert-manager
  version: 1.17.2
  repo: https://charts.jetstack.io
  #valuesInline:
