apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: cert-manager-vault
spec:
  provider:
    vault:
      server: http://vault.vault.svc.cluster.local:8200
      path: secret
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes-rpi
          role: cert-manager-default
          serviceAccountRef:
            name: default
